### ISSUE TITLE
Some queries do not work on cosmos-sdk > 0.50 chains

### ISSUE THREAD

**Issue by freak12techno** [ping-pub/explorer#583]
Namely, at least these two:

1) https://cosmos.api.silknodes.io/cosmos/bank/v1beta1/supply/uatom - should be https://cosmos.api.silknodes.io/cosmos/bank/v1beta1/supply/by_denom?denom=uatom
2) https://cosmos.api.silknodes.io/cosmos/tx/v1beta1/txs?order_by=2&events=delegate.validator=%27cosmosvaloper1c4k24jzduc365kywrsvf5ujz4ya6mwympnc4en%27&pagination.limit=5&pagination.offset=0&pagination.count_total=true - should be now https://cosmos.api.silknodes.io/cosmos/tx/v1beta1/txs?order_by=2&query=delegate.validator=%27cosmosvaloper1c4k24jzduc365kywrsvf5ujz4ya6mwympnc4en%27&pagination.limit=5&pagination.offset=0&pagination.count_total=true

(Guess there should be a setting in config on which endpoint to use, otherwise updating it would break <= cosmos-sdk 0.47 chains)

**Comment by PFC-developer** [comment]
sorry for the lack of a PR

but the following will help with the account page

```
src/libs/client.ts

  async getTxsBySenderV50(sender: string, page?: PageRequest) {
    if(!page) page = new PageRequest()
    const query = `?order_by=2&query=message.sender='${sender}'&pagination.limit=${page.limit}&pagination.offset=${page.offset||0}`;
    return this.request(this.registry.tx_txs, {}, query);
  }

```
in src/modules/[chain]/account/[address].vue
```
line 28: const cosmosSdk =  blockchain.current?.versions.cosmosSdk||"unknown";
```
line 96 
```
  if (cosmosSdk.startsWith("v0.5")) {
    blockchain.rpc.getTxsBySenderV50(address).then((x) => {
      txs.value = x.tx_responses;
    });
  } else {
    blockchain.rpc.getTxsBySender(address).then((x) => {
      txs.value = x.tx_responses;
    });
  }
```
line: 123
```
  if (cosmosSdk.startsWith("v0.5")) {
    const receivedQuery = `?&pagination.reverse=true&query=coin_received.receiver='${address}'&pagination.limit=5`;
    blockchain.rpc.getTxs(receivedQuery, {}).then((x) => {
      recentReceived.value = x.tx_responses;
    });
  } else {
    const receivedQuery = `?&pagination.reverse=true&events=coin_received.receiver='${address}'&pagination.limit=5`;
    blockchain.rpc.getTxs(receivedQuery, {}).then((x) => {
      recentReceived.value = x.tx_responses;
    });
  }
}
```

you can also do a similar thing in /src/modules/[chain]/staking/[validator].vue

**Comment by liangping** [comment]
will fix it soon

**Comment by liangping** [comment]
fixed

**Comment by migueldingli1997** [comment]
Hi @liangping could you point me to the fix please? We're still experiencing this issue on a test deployment of this explorer.
